
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: INFO

spring:
  data:
    mongodb:
      uri: mongodb+srv://${USERNAME}:${PASSWORD}@${DB_NAME}.ne01c.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=${DB_NAME}