spring:
  application:
    name: forms-webapp
  data:
    mongodb:
      uri: mongodb://localhost:27017/forms-db

server:
  port: ${PORT:8080}


logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG


com:
  forms:
    signingKey: ${SIGNING_KEY:Li54Cpz9BvE1vpBPZIeu+dGo6ZQI0kXHz+TwWgPDACGvZOGzCdWKQ5rjckBt8wSA6twpnsfYaSRDaL/9lBsNQQ==}
    mail:
      webAppUrl: ${WEB_APP_URL:http://localhost:4200}
      sendGrid:
        apiKey: ${SENDGRID_API_KEY:API_KEY}
        fromEmail: ${SENDGRID_FROM:example@forms.com}
        fromName: "Best Surveys"
      welcomeTemplate:
        templateId: "d-a0bf1d25691e4b80913ef51f3e842408"
        requiredDynamicFields:
          - "title"
          - "dynamic_url"
      filledOutFormTemplate:
        templateId: "d-4c3d21efbaf449dc9fee36882b381f84"
        requiredDynamicFields:
          - "form_name"
          - "answers"